Repository daeuniverse/dae, pull requests merged in 2023-05, with the labels that each got.

#67 chore: update changelogs to include release-v0.1.8
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature-request.md
  CHANGELOGS.md
Labels: chore

#78 chore(Makefile): add export GOOS=linux to build on macos
  Makefile
Labels: chore

#77 feat: support `tcp_check_http_method`
  common/utils.go
  component/outbound/dialer/connectivity_check.go
  component/sniffing/http.go
  component/sniffing/sniffing_bench_test.go
  config/config.go
  config/desc.go
  config/patch.go
  control/control_plane.go
  example.dae
Labels: feature

#85 chore: add editorconfig
  .editorconfig
Labels: chore

#86 chore: add pull_request_template
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: chore

#84 patch: search geodata at same dir with config first
  common/assets/assets.go
Labels: patch

#88 chore(changelog): `v0.1.9-patch.1` and `v0.1.10rc`
  CHANGELOGS.md
  README.md
Labels: changelogs

#93 ci: add check-docs workflow
  .autocorrectrc
  .github/workflows/build.yml
  .github/workflows/check-docs.yml
  .github/workflows/docker.yml
  .gitignore
  .markdownlint-cli2.jsonc
  README.md
  docs/commit-msg-guide.md
  docs/dns.md
  docs/getting-started/README.md
  docs/getting-started/README_zh.md
  docs/getting-started/build-by-yourself.md
  docs/getting-started/external-dns.md
  docs/getting-started/kernel-parameters.md
  docs/getting-started/kernel-upgrade.md
  docs/getting-started/other-proxy-protocol_zh.md
  docs/getting-started/reload-and-suspend.md
  docs/getting-started/run-as-daemon.md
  docs/getting-started/run-on-macos.md
  docs/getting-started/troubleshooting.md
  docs/how_it_works_zh.md
  docs/routing.md
  package-lock.json
  package.json
Labels: ci, do-not-merge

#94 feat: add uTLS support
  component/outbound/dialer/dialer.go
  component/outbound/dialer/trojan/trojan.go
  component/outbound/dialer/v2ray/v2ray.go
  component/outbound/transport/tls/tls.go
  component/outbound/transport/tls/utls.go
  config/config.go
  config/desc.go
  control/control_plane.go
  example.dae
  go.mod
  go.sum
Labels: feature

#95 refactor: move insert.sh to ./hack/test
  .github/workflows/docker.yml
  hack/test/insert.sh
Labels: refactor

#99 fix(dns): mismatched qname matching rules
  common/consts/dns.go
  component/dns/request_routing.go
  component/dns/response_routing.go
Labels: feature

#101 ci(hack): add config-doc-generator
  .github/workflows/check-docs.yml
  docs/.gitignore
  docs/sync/.gitkeep
  docs/templates/example-config.md
  example.dae
  hack/ci/config-doc-generator.py
Labels: ci, hack

#98 feat: support geosite attr
  component/routing/optimizer.go
  docs/dns.md
Labels: feature
