Repository daeuniverse/dae, pull requests merged in 2023-07, with the labels that each got.

#172 chore: expose the routable dialer for dae-wing
  control/tcp.go
Labels: chore, tested

#173 fix: samba not work
  control/kern/tproxy.c
Labels: fix, tested

#170 ci(generate-changelogs): add control on whether to write to issue page
  .github/workflows/generate-changelogs.yml
Labels: ci, tested

#167 optimize(dns): cache all qtype (not only a/aaaa)
  control/dns_control.go
Labels: optimize, tested

#166 feat: support to bind to lan lazily and re-bind to lan
  control/control_plane.go
  control/control_plane_core.go
Labels: feature, tested

#180 feat: support unknown qtype and upgrade go mod
  component/dns/function_parser.go
  go.mod
  go.sum
Labels: feature, tested

#181 chore: suppress LinkSubscribe error
  control/control_plane_core.go
Labels: chore, tested

#176 feat: support tuic v5
  component/outbound/dialer/tuic/tuic.go
  component/outbound/outbound.go
  control/tcp.go
  control/udp_endpoint.go
  docs/getting-started/other-proxy-protocol_zh.md
  go.mod
  go.sum
Labels: feature, tested

#188 refactor(dns): replace dnsmessage with miekg/dns
  common/netutils/dns.go
  common/netutils/ip46.go
  common/netutils/ip46_test.go
  common/utils.go
  component/dns/dns.go
  component/dns/function_parser.go
  component/dns/request_routing.go
  component/dns/response_routing.go
  component/outbound/dialer/connectivity_check.go
  component/outbound/dialer/socks/socks_test.go
  component/outbound/dialer_group_test.go
  control/control_plane.go
  control/control_plane_core.go
  control/dns_cache.go
  control/dns_control.go
  control/dns_utils.go
  control/udp.go
  control/udp_endpoint.go
  go.mod
  go.sum
Labels: refactor, tested

#186 ci: update workflow naming standards
  .github/workflows/check-docs.yml
  .github/workflows/pr-build.yml
  .github/workflows/sync-docs.yml
Labels: ci, tested

#185 docs(readme/badges): make release-badge updated on the fly
  README.md
Labels: documentation, tested

#179 refactor(/docs): rework documentation structure layout
  README.md
  docs/en/README.md
  docs/en/configuration/dns.md
  docs/en/configuration/external-dns.md
  docs/en/configuration/routing.md
  docs/en/development/commit-msg-guide.md
  docs/en/development/contribute.md
  docs/en/how-it-works.md
  docs/en/proxy-protocols.md
  docs/en/troubleshooting.md
  docs/en/tutorials/run-on-macos.md
  docs/en/user-guide/build-by-yourself.md
  docs/en/user-guide/kernel-parameters.md
  docs/en/user-guide/kernel-upgrade.md
  docs/en/user-guide/reload-and-suspend.md
  docs/en/user-guide/run-as-daemon.md
  docs/zh/README.md
  docs/zh/how-it-works.md
  docs/zh/proxy-protocols.md
  example.dae
  hack/ci/config-doc-generator.py
  hack/mock/insert.sh
  hack/sync/.gitkeep
  hack/templates/example-config.md
Labels: documentation, refactor

#165 fix(wss): allow_insecure and sni not work
  component/outbound/transport/ws/ws.go
Labels: fix

#189 ci: add daily-build workflow
  .github/workflows/daily-build.yml
Labels: ci

#119 feat: latency-based failover
  common/utils.go
  component/outbound/dialer/alive_dialer_set.go
  component/outbound/dialer/annotation.go
  component/outbound/dialer/connectivity_check.go
  component/outbound/dialer/dialer.go
  component/outbound/dialer/utils.go
  component/outbound/dialer_group.go
  component/outbound/filter.go
  config/config.go
  config/parser.go
  control/control_plane.go
  example.dae
  pkg/config_parser/config_parser.go
  pkg/config_parser/error.go
  pkg/config_parser/section.go
  pkg/config_parser/walker.go
  pkg/geodata/protoext/extensions.pb.go
Labels: feature, priority/high, tested

#203 fix: truncated dns resp
  common/consts/net.go
  common/netutils/dns.go
  control/control_plane.go
  control/dns_control.go
  control/udp_endpoint.go
  go.mod
  go.sum
Labels: fix, tested

#205 docs: demise dae.v2raya.org
  README.md
Labels: documentation, priority/high

#206 docs(run-on-alpine.md)Add Alpine guide
  docs/en/tutorials/run-on-alpine.md
Labels: documentation

#207 fix: No AddrPort presented
  control/control_plane.go
Labels: fix, tested

#198 ci(daily-build): update cron schedule
  .github/workflows/daily-build.yml
Labels: ci, priority/low

#208 ci(build,daily-build.yml): adhere to naming convention
  .github/workflows/build.yml
  .github/workflows/daily-build.yml
Labels: ci, not-yet-tested

#202 chore(pr_template): add test result section
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#204 fix/optimize/refactor(udp): fix potential stuck UDP and optimize reroute logic
  common/consts/dialer.go
  control/dns_control.go
  control/tcp.go
  control/udp.go
  control/udp_endpoint.go
  go.mod
  go.sum
Labels: fix, optimize, priority/high, tested

#209 ci(pr-build): use pr.head.sha as default ref
  .github/workflows/pr-build.yml
  .github/workflows/seed-build.yml
Labels: ci, hotfix, priority/high, tested

#210 ci/fix(seed-build): catch non-pr condition
  .github/workflows/seed-build.yml
Labels: fix, ci, priority/high

#214 ci(pr-build): fix default branch for seed workflow
  .github/workflows/pr-build.yml
Labels: ci, priority/high

#215 ci(pr-build): don't trigger workflow for draft PRs
  .github/workflows/pr-build.yml
Labels: ci, priority/high

#216 ci/fix(build): add ref input (required)
  .github/workflows/build.yml
Labels: fix, ci, priority/high

#219 feat/chore: add log file/refine code/add tip for no-load
  .gitignore
  cmd/run.go
  common/consts/ebpf.go
  component/outbound/dialer_group_test.go
  control/control_plane.go
  control/tcp.go
  control/udp.go
  go.mod
  go.sum
  pkg/logger/logger.go
Labels: chore, tested

#220 ci/fix(daily-build): add missing ref input
  .github/workflows/daily-build.yml
Labels: fix, ci, priority/high

#141 fix(dns): should reject with nx instead of 0.0.0.0
  control/control_plane.go
  control/dns_cache.go
  control/dns_control.go
Labels: fix, priority/low, tested

#218 ci/feat(build,pr-build,seed-build): integrate check runs to report build status
  .github/workflows/build.yml
  .github/workflows/daily-build.yml
  .github/workflows/pr-build.yml
  .github/workflows/seed-build.yml
Labels: feature, ci, priority/high, tested

#222 ci/hotfix(seed-build): add condition to run report-result
  .github/workflows/seed-build.yml
Labels: ci, hotfix, priority/high

#223 ci/hotfix(build): inherit secret
  .github/workflows/build.yml
  .github/workflows/seed-build.yml
Labels: ci, hotfix, tested

#221 fix: support to bind dae to wg lan (and other tun)
  common/consts/ebpf.go
  control/control_plane.go
  control/control_plane_core.go
  control/kern/tproxy.c
Labels: fix, tested

#225 fix(ebpf): udp problem caused by #221 by accident
  control/kern/tproxy.c
Labels: fix, priority/high, tested

#230 ci(seed-build): checkout codebase based on ref
  .github/workflows/seed-build.yml
Labels: ci, priority/high

#229 feat(vmess/vless): support network h2
  component/outbound/dialer/v2ray/v2ray.go
  docs/en/proxy-protocols.md
  go.mod
  go.sum
Labels: feature, tested

#232 optimize(vmess): auto choose cipher instead of aes-128-gcm
  component/outbound/dialer/v2ray/cipher.go
  component/outbound/dialer/v2ray/v2ray.go
Labels: optimize, tested

#234 chore: update codeowners
  CODEOWNERS
Labels: chore

#235 feat/refactor: support the node-level proxy chain
  component/outbound/dialer/block.go
  component/outbound/dialer/dialer.go
  component/outbound/dialer/direct.go
  component/outbound/dialer/http/http.go
  component/outbound/dialer/register.go
  component/outbound/dialer/shadowsocks/shadowsocks.go
  component/outbound/dialer/shadowsocksr/shadowsocksr.go
  component/outbound/dialer/socks/socks.go
  component/outbound/dialer/socks/socks_test.go
  component/outbound/dialer/trojan/trojan.go
  component/outbound/dialer/tuic/tuic.go
  component/outbound/dialer/v2ray/v2ray.go
  component/outbound/filter.go
  component/outbound/outbound.go
  component/outbound/transport/simpleobfs/dialer.go
  component/outbound/transport/simpleobfs/simpleobfs.go
  component/outbound/transport/tls/dialer.go
  component/outbound/transport/tls/tls.go
  component/outbound/transport/ws/dialer.go
  component/outbound/transport/ws/ws.go
  control/control_plane.go
  example.dae
  go.mod
  go.sum
Labels: feature, tested

#233 optimize: pull subscriptions using custom UA
  cmd/cmd.go
  common/subscription/subscription.go
  config/config.go
Labels: optimize, tested

#237 hotfix: fix subscription pulling panic caused by #233
  common/subscription/subscription.go
Labels: hotfix, tested

#239 ci/fix(generate_changelogs): remove desp for dry_run input
  .github/workflows/generate-changelogs.yml
Labels: fix, ci, tested

#241 docs: refine protocol support and alpine installation
  docs/en/README.md
  docs/en/proxy-protocols.md
  docs/zh/README.md
  example.dae
Labels: documentation

#243 docs: create zh global and dns docs
  docs/zh/configuration/dns.md
Labels: documentation

#247 docs: create zh routing docs
  docs/zh/configuration/routing.md
Labels: documentation
