Repository daeuniverse/dae, pull requests merged in 2023-11, with the labels that each got.

#346 feat: support --abort for reload and suspend
  cmd/cmd.go
  cmd/reload.go
  cmd/run.go
  cmd/suspend.go
  control/control_plane.go
Labels: feature, tested

#352 chore: add bash completion
  install/shell-completion/dae.bash
Labels: chore, tested

#353 chore: add zsh completion
  install/shell-completion/dae.zsh
Labels: chore, tested

#301 optimize(udp)/fix(quicSniffer): optimize performance of udp and fix a potential panic of quic
  common/netutils/dns.go
  component/dns/dns.go
  component/dns/upstream.go
  component/outbound/dialer/connectivity_check.go
  component/outbound/dialer/sockopt.go
  component/outbound/dialer_group.go
  component/sniffing/conn_sniffer.go
  component/sniffing/http.go
  component/sniffing/internal/quicutils/cipher.go
  component/sniffing/internal/quicutils/cipher_test.go
  component/sniffing/internal/quicutils/relocation.go
  component/sniffing/quic.go
  component/sniffing/quic_bench_test.go
  component/sniffing/quic_test.go
  component/sniffing/sniffer.go
  component/sniffing/sniffing.go
  component/sniffing/tls.go
  component/sniffing/tls_test.go
  config/config_merger.go
  control/anyfrom_pool.go
  control/control_plane.go
  control/dns_control.go
  control/packet_sniffer_pool.go
  control/packet_sniffer_pool_test.go
  control/udp.go
  control/udp_endpoint_pool.go
  docs/en/README.md
  docs/zh/README.md
  example.dae
  go.mod
  go.sum
  main.go
  pkg/trie/trie.go
Labels: fix

#356 feat(cmd): extend --version print info
  cmd/cmd.go
Labels: feature
