Repository daeuniverse/dae, pull requests merged in 2023-04, with the labels that each got.

#54 doc: add badges and contribution guide
  README.md
  docs/commit-msg-guide.md
  docs/contribute.md
Labels: documentation

#55 chore: add changelogs
  CHANGELOGS.md
Labels: changelogs

#56 fix(changelogs.md): fix syntax
  CHANGELOGS.md
Labels: fix, changelogs

#57 chore: update changelogs
  CHANGELOGS.md
Labels: changelogs

#59 chore: add pre-commit hook
  .pre-commit-config.yaml
  docs/contribute.md
Labels: chore

#62 chore: add issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/support-request.md
Labels: chore

#64 chore(codeowner): update ownership
  CODEOWNERS
Labels: chore

#63 optimize: cache NXDomain and reject with 0.0.0.0/::
  common/netutils/dns.go
  control/control_plane_core.go
  control/dns_cache.go
  control/dns_control.go
Labels: optimize
