Repository daeuniverse/dae, pull requests merged in 2023-08, with the labels that each got.

#251 optimize: force to choose one if there is only one node in the group
  component/outbound/dialer_group.go
Labels: optimize, tested

#256 feat(juicity): support certificate pinning
  common/utils.go
  component/outbound/dialer/juicity/juicity.go
  go.mod
  go.sum
Labels: feature, not-yet-tested

#257 fix: bad ipversion selection caused by #251
  cmd/run.go
  common/bitlist/bitlist.go
  common/netutils/dns.go
  common/netutils/ip46.go
  common/netutils/ip46_test.go
  common/utils.go
  component/dns/upstream.go
  component/outbound/dialer/alive_dialer_set.go
  component/outbound/dialer/block.go
  component/outbound/dialer/connectivity_check.go
  component/outbound/dialer/dialer.go
  component/outbound/dialer/direct.go
  component/outbound/dialer/http/http.go
  component/outbound/dialer/juicity/juicity.go
  component/outbound/dialer/register.go
  component/outbound/dialer/shadowsocks/shadowsocks.go
  component/outbound/dialer/shadowsocksr/shadowsocksr.go
  component/outbound/dialer/socks/socks.go
  component/outbound/dialer/socks/socks_test.go
  component/outbound/dialer/trojan/trojan.go
  component/outbound/dialer/tuic/tuic.go
  component/outbound/dialer/v2ray/v2ray.go
  component/outbound/dialer_group.go
  component/outbound/dialer_group_test.go
  component/outbound/outbound.go
  component/outbound/transport/simpleobfs/http.go
  component/outbound/transport/simpleobfs/simpleobfs.go
  component/outbound/transport/simpleobfs/tls.go
  component/outbound/transport/tls/tls.go
  component/outbound/transport/ws/ws.go
  component/sniffing/internal/quicutils/cipher.go
  component/sniffing/internal/quicutils/hkdf.go
  component/sniffing/internal/quicutils/relocation.go
  component/sniffing/quic.go
  component/sniffing/sniffing_bench_test.go
  control/control_plane.go
  control/dns_control.go
  control/tcp.go
  control/udp.go
  control/udp_endpoint.go
  go.mod
  go.sum
  pkg/trie/trie.go
Labels: fix, tested

#262 fix: caddy cannot accept connections
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  .github/workflows/seed-build.yml
  control/bpf_utils.go
  control/kern/tproxy.c
  docs/en/troubleshooting.md
  docs/en/user-guide/build-by-yourself.md
Labels: fix, tested

#258 feat: add meek
  component/outbound/dialer/v2ray/v2ray.go
  control/control_plane.go
  docs/en/proxy-protocols.md
  docs/zh/proxy-protocols.md
  go.mod
  go.sum
Labels: feature, tested

#265 optimize(juicity): support Base64URLEncoding for PinnedCertchainSha256
  component/outbound/dialer/juicity/juicity.go
Labels: optimize, tested

#267 chore/refactor: rework issue_templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/proposal.yml
  .github/ISSUE_TEMPLATE/support-request.md
  .github/ISSUE_TEMPLATE/support-request.yml
Labels: chore, refactor

#269 chore(pr_template): update headers
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#270 chore: upgrade quic-go to 0.37.4 to support go1.21
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  .github/workflows/seed-build.yml
  Makefile
  cmd/run.go
  common/netutils/dns.go
  component/outbound/dialer/connectivity_check.go
  component/outbound/dialer/trojan/trojan.go
  component/outbound/dialer/v2ray/v2ray.go
  control/dns_control.go
  control/tcp.go
  control/udp_endpoint.go
  go.mod
  go.sum
Labels: chore

#271 fix: rebinding wg/tun not work
  control/control_plane.go
  control/control_plane_core.go
Labels: fix, tested

#272 chore: amd64 and arm64 use PIE build mode by default
  Makefile
Labels: chore

#273 ci/chore: remove the buildmode specified in CI
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  .github/workflows/seed-build.yml
Labels: chore, tested

#277 ci(release): draft release v0.2.4
  CHANGELOGS.md
Labels: release:auto

#282 ci/hotfix: demise buildarg=pie
  Makefile
Labels: ci, hotfix

#288 feat: dae can call now
  cmd/honk.go
Labels: feature, not-yet-tested

#292 feat: support ToS routing rule
  cmd/honk.go
  common/consts/ebpf.go
  common/consts/routing.go
  component/routing/function_parser.go
  control/dns_control.go
  control/kern/tproxy.c
  control/routing_matcher_builder.go
  control/routing_matcher_userspace.go
  control/tcp.go
  control/udp.go
  control/utils.go
  docs/en/configuration/routing.md
  docs/zh/configuration/routing.md
  pkg/ebpf_internal/rawsock_linux.go
Labels: feature, tested

#289 chore: honk with sound
  cmd/honk.go
Labels: chore

#294 refactor/fix: match dscp instead of tos
  cmd/honk.go
  common/consts/ebpf.go
  common/consts/routing.go
  component/routing/function_parser.go
  control/control_plane.go
  control/dns_control.go
  control/kern/tproxy.c
  control/routing_matcher_builder.go
  control/routing_matcher_userspace.go
  control/tcp.go
  control/udp.go
  control/utils.go
  docs/en/configuration/routing.md
  docs/zh/configuration/routing.md
  go.mod
  go.sum
Labels: fix, tested

#297 chore: bump quic-go to v0.38.0
  go.mod
  go.sum
Labels: chore

#300 docs(en): update how-it-works
  docs/en/how-it-works.md
Labels: documentation

#303 chore: close file descriptor & remove duplicated error handle
  common/subscription/subscription.go
Labels: chore
