Repository daeuniverse/dae, pull requests merged in 2023-06, with the labels that each got.

#103 ci: docs synchronization
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/workflows/check-docs.yml
  .github/workflows/sync-docs.yml
Labels: ci, hack

#108 fix(config_parser): potential panic due to out of index
  pkg/config_parser/walker.go
Labels: fix

#112 chore: release v0.1.10
  CHANGELOGS.md
  README.md
Labels: changelogs

#80 feat: support iptables tproxy
  .github/workflows/build.yml
  Makefile
  cmd/run.go
  common/consts/ebpf.go
  common/netutils/dns.go
  common/netutils/ip46.go
  common/subscription/subscription.go
  common/utils.go
  component/dns/dns.go
  component/dns/upstream.go
  component/outbound/dialer/connectivity_check.go
  component/outbound/dialer/trojan/trojan.go
  component/outbound/transport/simpleobfs/simpleobfs.go
  component/outbound/transport/tls/tls.go
  component/outbound/transport/ws/ws.go
  config/config.go
  config/desc.go
  control/control_plane.go
  control/dns_control.go
  control/kern/tproxy.c
  control/tcp.go
  control/udp.go
  control/utils.go
  example.dae
  go.mod
  go.sum
Labels: feature

#109 fix(trojan): potential panic due to incorrect n returned by ReadFrom
  go.mod
  go.sum
Labels: fix

#117 chore: release v0.2.0rc1 (#115)
  CHANGELOGS.md
  README.md
Labels: changelogs

#120 fix(trojan): potential panic due to invalid packet control data
  go.mod
  go.sum
Labels: fix

#125 chore(changelogs-v0.2.0rc1): apply minor fix
  CHANGELOGS.md
Labels: changelogs

#126 chore(Makefile): support submodules
  .gitignore
  Makefile
Labels: chore

#144 chore: allow to modify app name and assets dir name
  common/assets/assets.go
  common/consts/app.go
  common/consts/ebpf.go
Labels: chore

#148 fix(socks5): udp problem
  component/outbound/dialer/socks/socks_test.go
  go.mod
  go.sum
Labels: fix, priority/high

#146 chore(pr_template): correct a typo
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore, priority/low

#149 fix(group): policy 'fixed' parsing
  component/outbound/dialer_selection_policy.go
Labels: hotfix, priority/high

#151 fix/chore(grpc): allow insecure
  go.mod
  go.sum
Labels: fix, priority/high

#153 feat(config): support IgnoreZero option for config.Marhsaller
  config/marshal.go
Labels: feature

#147 docs(getting-started): add ref to run-as-daemon
  docs/getting-started/README.md
  docs/getting-started/README_zh.md
  docs/getting-started/build-by-yourself.md
  docs/getting-started/run-as-daemon.md
Labels: documentation, priority/high

#155 fix: bad connectivity check of dns(udp) caused by #80
  component/outbound/dialer/connectivity_check.go
  control/control_plane.go
Labels: fix, tested

#159 ci: add generate-changelogs workflow
  .github/workflows/generate-changelogs.yml
  CHANGELOGS.md
Labels: ci

#162 fix/ci: fix argument list too lang due to `packed` and use clang-15
  .github/workflows/build.yml
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  control/kern/tproxy.c
Labels: fix, ci, tested

#163 ci(release): draft release v0.2.0rc4
  CHANGELOGS.md
  README.md
Labels: tested, release

#164 fix: should allow fallbacking ip version if dialing domain
  common/consts/ebpf.go
  component/outbound/dialer_group.go
  control/connectivity.go
  control/control_plane.go
  control/tcp.go
  control/udp.go
Labels: fix, tested
