Repository daeuniverse/dae, pull requests merged in 2023-09, with the labels that each got.

#305 docs: improve docs about pppoe and mark
  cmd/run.go
  common/consts/ebpf.go
  control/control_plane_core.go
  control/kern/tproxy.c
  docs/en/troubleshooting.md
  hack/mock/insert.sh
Labels: documentation, tested

#307 optimize: latencyString shows realLatency(+offset)
  component/outbound/dialer/alive_dialer_set.go
  component/outbound/dialer/utils.go
Labels: feature, not-yet-tested

#311 chore(release): add changelogs entry for v0.3.0
  CHANGELOGS.md
Labels: chore

#314 ci(generate-changelogs): update default assignees list
  .github/workflows/generate-changelogs.yml
Labels: ci

#319 feat/optimize: print SubscriptionTag in AliveDialerSet::printLatencies()
  component/outbound/dialer/alive_dialer_set.go
  component/outbound/dialer/dialer.go
  component/outbound/dialer/register.go
  component/outbound/filter.go
Labels: feature, optimize, tested

#320 chore(Dockerfile): upgrade golang and clang (https://github.com/daeuniverse/daed/issues/250)
  Dockerfile
Labels: ci, not-yet-tested
