Repository daeuniverse/dae, pull requests merged in 2024-12, with the labels that each got.

#708 feat(vision): support xudp
  go.mod
  go.sum
Labels: feature, tested

#712 docs(run-on-alpine.md): update for Alpine's kernel changes
  docs/en/tutorials/run-on-alpine.md
  docs/zh/tutorials/run-on-alpine.md
Labels: documentation

#717 docs: disable Encrypted ClientHello to avoid affecting traffic split
  docs/en/README.md
  docs/en/configuration/dns.md
  docs/zh/README.md
  docs/zh/configuration/dns.md
Labels: documentation

#719 fix: must_rules cause entire match_set to become must.
  control/kern/tproxy.c
Labels: fix, tested

#721 ci: add linux packages & minimize archive size
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  install/package_after_install.sh
  install/package_after_remove.sh
Labels: ci, tested

#723 test: fix CO-RE issue on kernel 6.9 and above in eBPF tests
  control/kern/tests/bpf_test.c
Labels: tested

#722 feat: enhance privilege elevation logic
  cmd/internal/su.go
  cmd/reload.go
  cmd/run.go
  cmd/sysdump.go
  control/dns_control.go
  trace/trace.go
Labels: tested, triage/needs-user-input
