Repository daeuniverse/dae, pull requests merged in 2024-08, with the labels that each got.

#588 fix(cmd/run.go): always check whether network online
  cmd/run.go
Labels: tested

#605 chore(example.dae): add hy2 in comments
  example.dae
Labels: documentation

#600 optimize(bpf): Alternative way to avoid parsing packet at dae0
  control/kern/tproxy.c
Labels: optimize, tested

#603 docs: update persistent script
  docs/en/user-guide/persistent-subscription.md
Labels: documentation

#601 feat: add MPTCP support
  cmd/run.go
  common/utils.go
  component/outbound/dialer/connectivity_check.go
  config/config.go
  config/desc.go
  control/control_plane.go
  control/dns_control.go
  control/tcp.go
  control/udp.go
  example.dae
  go.mod
  go.sum
Labels: feature, tested
