Repository daeuniverse/dae, pull requests merged in 2024-03, with the labels that each got.

#458 feat(bpf): implement stack bypass
  .github/workflows/kernel-test.yml
  cmd/run.go
  config/config.go
  control/anyfrom_pool.go
  control/bpf_utils.go
  control/control_plane.go
  control/control_plane_core.go
  control/kern/tproxy.c
  control/netns_utils.go
  control/udp.go
  docs/en/README.md
  docs/en/how-it-works.md
  docs/zh/README.md
  example.dae
  go.mod
  go.sum
Labels: documentation, feature

#465 ci: update ci modules using nodejs to latest
  .github/workflows/kernel-test.yml
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  .github/workflows/seed-build.yml
  .github/workflows/sync-docs.yml
Labels: ci, tested

#466 patch/optimize(bpf): improve lan hijack datapath performance
  .github/workflows/kernel-test.yml
  control/kern/tproxy.c
  control/netns_utils.go
Labels: patch, optimize, tested

#477 style: format bpf c code using kernel checkpatch.pl
  .github/workflows/lint.yml
  Makefile
  control/kern/tproxy.c
  scripts/checkpatch.pl
Labels: style

#483 fix: Fix bpf CO-RE issue on 6.9
  control/kern/tproxy.c
Labels: tested

#480 fix(bpf): revert using bpf_redirect_peer
  control/kern/tproxy.c
Labels: tested

#481 patch/optimize(bpf): improve wan tcp hijack datapath performance
  common/consts/ebpf.go
  control/control_plane.go
  control/control_plane_core.go
  control/kern/tproxy.c
  docs/en/README.md
  docs/zh/README.md
Labels: documentation, feature, optimize, tested, bpf
