Repository daeuniverse/dae, pull requests merged in 2024-11, with the labels that each got.

#649 feat(dns): support DoH, DoT, DoH3, DoQ
  component/dns/dns.go
  component/dns/upstream.go
  control/dns.go
  control/dns_control.go
Labels: feature, tested

#687 docs(dns): add docs for #649
  docs/en/configuration/dns.md
  docs/zh/configuration/dns.md
  example.dae
Labels: documentation

#688 docs(dns): fix typo
  docs/en/configuration/dns.md
  docs/zh/configuration/dns.md
  example.dae
Labels: documentation

#700 optimize: reduce memory usage by reading kallsyms only in the trace command
  cmd/trace.go
  trace/kallsyms.go
Labels: optimize, tested

#697 fix: update sources in `desc.go`
  config/desc.go
Labels: documentation

#692 chore: more detail of Choose DNS path log
  control/control_plane.go
Labels: chore, tested

#707 fix: minimal upgrade panjf2000/ants dependency to v2.0.0
  control/udp_task_pool.go
  go.mod
  go.sum
Labels: fix, tested
