Repository daeuniverse/dae, pull requests merged in 2024-06, with the labels that each got.

#540 fix: support to report all error when reloading
  cmd/run.go
  pkg/config_parser/section.go
Labels: fix, tested

#532 chore: Add a global config to enable pprof
  cmd/run.go
  config/config.go
  example.dae
Labels: chore

#541 docs: add protocols uri schema
  docs/en/proxy-protocols.md
  docs/zh/proxy-protocols.md
Labels: documentation

#531 docs: update arch installation
  docs/en/README.md
  docs/zh/README.md
Labels: documentation

#539 fix: incidental packet drop and weird UDP state maintaining
  control/control_plane.go
  control/kern/tproxy.c
  control/packet_sniffer_pool.go
  control/packet_sniffer_pool_test.go
  control/udp.go
  control/udp_endpoint_pool.go
  control/udp_task_pool.go
  go.mod
  go.sum
Labels: fix, tested

#547 ci: update action-gh-release to v2
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
Labels: ci, tested

#550 fix/chore(hy2): update outbound submodule to fix userpass auth
  go.mod
  go.sum
Labels: fix, chore, tested

#561 docs: Update build-by-yourself.md
  docs/en/user-guide/build-by-yourself.md
Labels: documentation, tested

#558 docs(protocols): add hysteria2
  docs/en/proxy-protocols.md
  docs/zh/proxy-protocols.md
Labels: documentation
