Repository daeuniverse/dae, pull requests merged in 2024-09, with the labels that each got.

#615 feat: support ipip tunnel as lan/wan interface
  control/control_plane_core.go
Labels: feature, tested

#623 feat: allow group override global node connectivity check
  component/outbound/dialer/connectivity_check.go
  component/outbound/dialer/dialer.go
  config/config.go
  config/desc.go
  control/control_plane.go
  example.dae
Labels: feature, tested

#573 feat(dialer): support reality (without udp support)
  control/tcp.go
  go.mod
  go.sum
Labels: feature, tested

#627 docs: add reality tcp support to proxy-protocols
  docs/en/proxy-protocols.md
  docs/zh/proxy-protocols.md
Labels: documentation

#628 optimize: replace c arithmetic operators with bitwise ones
  control/kern/tproxy.c
Labels: tested

#633 refactor: improve code readability of struct initialization
  control/kern/tproxy.c
Labels: refactor, tested

#634 refactor: remove redundant assignments
  control/kern/tproxy.c
Labels: refactor, tested

#637 patch: revert: refactor: improve code readability of struct initialization
  control/kern/tproxy.c
Labels: fix, tested

#641 refactor: reuse existing functions & format code
  control/kern/tproxy.c
Labels: refactor, tested

#646 fix: compatible issue when DNS msg not be compressed
  control/dns_control.go
Labels: fix, tested

#650 fix(sniffer): remove useless EOF warning logs printing
  component/sniffing/sniffer.go
Labels: fix, tested

#624 fix: connection leaks
  .gitignore
  cmd/run.go
  common/netutils/dns.go
  component/outbound/dialer/connectivity_check.go
  control/dns_control.go
  control/tcp.go
  control/udp_endpoint_pool.go
  go.mod
  go.sum
  pkg/logger/logger.go
Labels: fix, tested

#645 feat: support bandwidth configuration
  component/outbound/dialer/dialer.go
  config/config.go
  example.dae
  go.mod
  go.sum
Labels: feature, tested

#652 fix(vless): allow empty flow as ordinary tls
  go.mod
  go.sum
Labels: fix, tested

#632 feat(trace): add drop-only option
  cmd/trace.go
  trace/trace.go
Labels: feature, tested

#663 fix(hy2): dialer regression introduced by #645 pr
  go.mod
  go.sum
Labels: fix, tested

#664 docs: Google DNS should use dns.google instead of dns.google.com
  component/routing/domain_matcher/benchmark_test.go
  config/config.go
  docs/en/README.md
  docs/en/configuration/dns.md
  docs/en/configuration/external-dns.md
  docs/en/configuration/routing.md
  docs/en/configuration/separate-config.md
  docs/en/tutorials/run-on-macos.md
  docs/zh/README.md
  docs/zh/configuration/dns.md
  docs/zh/configuration/routing.md
  example.dae
Labels: documentation
