Repository daeuniverse/dae, pull requests merged in 2024-07, with the labels that each got.

#577 docs: persistent subscription
  docs/en/user-guide/persistent-subscription.md
Labels: documentation

#570 fix(udp_task_pool): panic: close of closed channel
  control/udp_task_pool.go
Labels: fix, tested

#572 feat: add sysdump as subcommand
  cmd/sysdump.go
  go.mod
  go.sum
Labels: feature, tested

#569 fix: unknown tls implementation
  go.mod
  go.sum
Labels: fix, tested
