Repository daeuniverse/dae, pull requests merged in 2024-10, with the labels that each got.

#682 fix(routing): Fix MergeAndSortRulesOptimizer
  component/routing/optimizer.go
Labels: fix, tested

#580 refactor/optimize(bpf): rework bpf route with bpf_loop
  .github/workflows/kernel-test.yml
  Makefile
  common/consts/ebpf.go
  control/control_plane.go
  control/kern/tproxy.c
  docs/en/README.md
  docs/zh/README.md
  go.mod
  go.sum
  hack/mock/insert.sh
Labels: documentation, optimize, refactor, tested

#666 feat/optimize(hy2): support human-readable bandwidth configuration
  component/outbound/dialer_group_test.go
  config/config.go
  example.dae
  go.mod
  go.sum
Labels: documentation, tested
