Repository daeuniverse/dae, pull requests merged in 2024-01, with the labels that each got.

#391 fix/chore: disable gso on client by default and upgrade softwind/quic-go
  control/anyfrom_pool.go
  control/control_plane.go
  go.mod
  go.sum
Labels: chore, tested

#388 fix: add _ into valid charset of ac machine
  component/routing/domain_matcher/benchmark_test.go
  go.mod
  go.sum
Labels: fix, tested

#386 ci: Add more kernel tests
  .github/workflows/kernel-test.yml
Labels: ci, not-yet-tested

#390 feat/refactor: refactor outbound and support v2ray-plugin
  component/outbound/dialer/block.go
  component/outbound/dialer/dialer.go
  component/outbound/dialer/direct.go
  component/outbound/dialer/http/http.go
  component/outbound/dialer/juicity/juicity.go
  component/outbound/dialer/register.go
  component/outbound/dialer/shadowsocks/shadowsocks.go
  component/outbound/dialer/shadowsocksr/shadowsocksr.go
  component/outbound/dialer/socks/socks.go
  component/outbound/dialer/socks/socks_test.go
  component/outbound/dialer/trojan/trojan.go
  component/outbound/dialer/tuic/tuic.go
  component/outbound/dialer/v2ray/cipher.go
  component/outbound/dialer/v2ray/v2ray.go
  component/outbound/dialer_group.go
  component/outbound/dialer_group_test.go
  component/outbound/outbound.go
  component/outbound/transport/simpleobfs/dialer.go
  component/outbound/transport/simpleobfs/http.go
  component/outbound/transport/simpleobfs/simpleobfs.go
  component/outbound/transport/simpleobfs/tls.go
  component/outbound/transport/tls/dialer.go
  component/outbound/transport/tls/tls.go
  component/outbound/transport/tls/utls.go
  component/outbound/transport/ws/conn.go
  component/outbound/transport/ws/dialer.go
  component/outbound/transport/ws/ws.go
  control/connectivity.go
  control/control_plane.go
  docs/en/proxy-protocols.md
  docs/zh/proxy-protocols.md
  go.mod
  go.sum
Labels: feature, refactor, tested

#376 Rewrite bpf spec before loading to avoid bpf map lookup during runtime
  control/bpf_utils.go
  control/control_plane.go
  control/kern/tproxy.c
Labels: triage/accepted

#392 ci(docker): remove support for armv6
  .github/workflows/docker.yml
Labels: ci, tested

#264 fix: running issue and no network on android
  common/netutils/dns.go
  component/dns/dns.go
  control/control_plane.go
Labels: fix, not-yet-tested

#401 fix(bpf): sk_lookup_udp for listener only
  control/kern/tproxy.c
Labels: tested

#402 chore: Build statically linked binary
  Makefile
Labels: chore, tested

#403 docs(troubleshooting.md): add firewalld related docs
  docs/en/troubleshooting.md
Labels: documentation

#420 feat: support to auto config firewall (firewalld)
  common/consts/ebpf.go
  config/config.go
  control/control_plane.go
  control/control_plane_core.go
  docs/en/README.md
  docs/zh/README.md
  example.dae
Labels: feature, tested

#414 fix: Workaround UDP port conflicts when another local process binds 53
  cmd/run.go
  control/netns_utils.go
  control/udp.go
  control/utils.go
Labels: fix, tested

#418 fix/docs: fix the first check failure and possible dns leaking
  component/outbound/dialer/connectivity_check.go
  component/outbound/dialer/dialer.go
  component/outbound/dialer_group_test.go
  component/outbound/filter.go
  control/control_plane.go
  docs/en/README.md
  docs/zh/README.md
  example.dae
Labels: documentation, fix, tested

#422 optimize: avoid conflict with potential local dns server
  control/anyfrom_pool.go
  control/udp.go
Labels: optimize, tested

#411 refactor/optimize: remove dead code
  common/consts/ebpf.go
  control/addr.go
  control/control.go
  control/control_plane_core.go
  control/dns_control.go
  control/kern/tproxy.c
  control/tcp.go
  control/udp.go
Labels: optimize, refactor, tested

#440 chore(generate-changelogs): update required reviewers list
  .github/workflows/generate-changelogs.yml
Labels: chore
