Repository daeuniverse/dae, pull requests merged in 2024-04, with the labels that each got.

#467 chore: Replace regexp with regexp2 for better filtering
  cmd/run.go
  component/outbound/filter.go
  go.mod
  go.sum
Labels: chore

#492 feat: add .clang-format file from torvalds/linux
  .clang-format
  .gitignore
  Makefile
  control/kern/tproxy.c
Labels: feature, tested

#494 fix: shoot ipv6 icmp redirects
  control/control_plane_core.go
  control/kern/tproxy.c
Labels: fix, tested

#495 fix: cannot use must in bracket in fallback
  config/config.go
Labels: fix, tested

#496 fix: Don't enable net.ipv6.conf.all.forwarding
  control/netns_utils.go
Labels: fix, tested

#503 fix/chore: update submodule outbound to fix panic in some edge cases
  cmd/run.go
  common/bitlist/bitlist.go
  common/netutils/dns.go
  common/netutils/ip46.go
  common/netutils/ip46_test.go
  common/utils.go
  component/dns/upstream.go
  component/outbound/dialer/alive_dialer_set.go
  component/outbound/dialer/block.go
  component/outbound/dialer/connectivity_check.go
  component/outbound/dialer/dialer.go
  component/outbound/dialer/direct.go
  component/outbound/dialer/register.go
  component/outbound/dialer_group.go
  component/outbound/dialer_group_test.go
  component/outbound/outbound.go
  component/sniffing/internal/quicutils/cipher.go
  component/sniffing/internal/quicutils/hkdf.go
  component/sniffing/quic.go
  component/sniffing/sniffer.go
  component/sniffing/sniffing_bench_test.go
  control/control_plane.go
  control/dns_control.go
  control/tcp.go
  control/udp.go
  control/udp_endpoint_pool.go
  go.mod
  go.sum
  pkg/trie/trie.go
Labels: fix, chore, tested

#510 chore(dae.service): set TimeoutStartSec=120 instead of 10
  install/dae.service
Labels: tested
