Repository daeuniverse/dae, pull requests merged in 2025-02, with the labels that each got.

#746 feat: support link/ppp & link/tun
  control/control_plane_core.go
  control/kern/tproxy.c
  docs/en/README.md
  docs/en/troubleshooting.md
  docs/zh/README.md
Labels: documentation, feature, tested

#743 chore: upgrade quic-go to v0.49.0
  .gitignore
  control/dns.go
  go.mod
  go.sum
Labels: chore

#726 feat: subfile as sublink fallback
  cmd/run.go
  common/subscription/subscription.go
  docs/en/user-guide/persistent-subscription.md
  example.dae
Labels: documentation, feature, tested

#747 fix: close of closed channel
  go.mod
  go.sum
Labels: fix, tested

#751 ci(kernel-test.yml): update checkout to v4.2
  .github/workflows/kernel-test.yml
Labels: ci, tested

#744 docs: add check command for fish shell
  docs/en/README.md
  docs/zh/README.md
Labels: documentation

#748 fix: panic due to goroutine setting returned error
  common/netutils/context_dialer.go
  common/netutils/dns.go
  common/netutils/ip46.go
  common/netutils/ip46_test.go
  component/dns/upstream.go
  component/outbound/dialer/connectivity_check.go
  component/sniffing/sniffer.go
  control/control_plane.go
  control/dns.go
Labels: fix, tested

#757 ci: add zip format for binary archives & adjust compression level
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
Labels: ci, tested
