Repository daeuniverse/dae, pull requests merged in 2025-05, with the labels that each got.

#784 feat: add fallback DNS
  cmd/run.go
  common/netutils/dns.go
  config/config.go
  go.mod
  go.sum
Labels: feature, tested

#802 fix: revert wrongly merged go mod changes
  go.mod
  go.sum
Labels: fix, tested

#811 ci(bpf-test): Test bpf against llvm 15-19
  .github/workflows/bpf-test.yml
Labels: ci, tested

#813 chore(cmd/config): fix typos
  cmd/run.go
  config/config.go
  example.dae
Labels: documentation, chore, tested

#782 fix: solve the problem that DNS dialer not perform switching & udp traffic stucks
  control/dns_control.go
  control/udp_task_pool.go
  control/udp_task_pool_test.go
  go.mod
  go.sum
Labels: fix, tested

#829 docs(example): add fallback resolver
  example.dae
Labels: documentation
