Repository daeuniverse/dae, pull requests merged in 2025-06, with the labels that each got.

#842 chore(bpf): Cleanup dead bpf code
  control/bpf_utils.go
  control/control_plane_core.go
  control/kern/tproxy.c
Labels: chore

#837 test(ci/kernel-test): Update kernels in ci
  .github/workflows/kernel-test.yml
Labels: tested

#844 fix(tproxy): refactor parse_transport and fix wrong ipv6 extension header offset calc
  control/kern/tproxy.c
Labels: fix, tested

#822 optimize(bpf): Load separate programs for L2/L3 netdev
  common/consts/ebpf.go
  control/control_plane_core.go
  control/kern/tests/bpf_test.c
  control/kern/tproxy.c
Labels: optimize, tested

#845 fix(bpf): Fix bpf timer
  control/kern/tproxy.c
Labels: fix, tested
